### ISSUE TITLE
Change bacon to return s3 object

### ISSUE THREAD

**Issue by evanjflack** [evanjflack/bacon#23]
"But I think the pro method would be to have it return an s3 object" - @EdJeeOnGitHub

**Comment by evanjflack** [comment]
Currently have print() and summary() methods. How should we change those/what other methods should we add?

**Comment by EdJeeOnGitHub** [comment]
I haven't had a chance to look at the code in detail yet but presumably we want to inherit all the stuff lm does so predict etc.

There's a list here: https://stat.ethz.ch/R-manual/R-devel/library/stats/html/lm.html

On the other hand it might not really be a natural fit as we want to return the 2x2 grid more than anything else I guess?


A default plot.bacon would probably be good?

**Comment by evanjflack** [comment]
If we wanted to have the function also estimate the two-way FE model then I think it makes sense to inherit lm stuff. I guess the question is do we want to include that, or should we just stick to the 2x2 grid and people can use  lm() or plm() to estimate the FE model.

**Comment by EdJeeOnGitHub** [comment]
I'm more inclined to keep it as small and modular as possible so we just stick to 2x2 rather than re-invent the wheel?

Maybe less fun this way though...


I guess if we go down modular route the next step is to look at including time-varying controls and profile any bottlenecks.

**Comment by evanjflack** [comment]
I agree, at least for now let's stick to 2x2.
