### ISSUE TITLE
Change data doesn't work

### ISSUE THREAD

**Issue by meichen1129** [evanjflack/bacon#77]
When I change another dataset (fake_data), and replace the variables and run, always noted that "Error: 'fake_data' is not an exported object from 'namespace:bacondecomp'",  I don't know how to deal with it.

**Comment by EdJeeOnGitHub** [comment]
Hi,

Could you share an example of your code so we can investigate?

A reproducible example (reprex) can be easily created following the instructions here: https://reprex.tidyverse.org/.

Thanks!

**Comment by kylebutts** [comment]
I assume @meichen1129 that you are copying and changing from the README:

```{r}
df_bacon <- bacon(incearn_ln ~ reform_math,
                  data = bacondecomp::fake_data,
                  id_var = "state",
                  time_var = "class")
```

The `bacondecomp::math_reform` is a dataset that is stored in the bacondecomp package. You don't need the `bacondecomp::` part:

```{r}
df_bacon <- bacon(incearn_ln ~ reform_math,
                  data = fake_data,
                  id_var = "state",
                  time_var = "class")
```
