### ISSUE TITLE
The only variable 'treated' is collinear with the fixed effects.

### ISSUE THREAD

**Issue by zhiyzuo** [evanjflack/bacon#82]
First of all, thank you for this package!

I was running this on my own data after TWFE with an attempt to see the breakdown of the treatment effects in different comparison groups but received this error:
```
Error: in fixest::feols(outcome ~ treated | time + id, data...:
 The only variable 'treated' is collinear with the fixed effects. In such
circumstances, the estimation is void.
Traceback:

1. bacon(formula = as.formula(bacon.fml), data = bacon.dat, id_var = "thread_id", 
 .     time_var = time.index)
2. fixest::feols(outcome ~ treated | time + id, data = data1)
3. stop_up(msg, up = fromGLM)
4. stop("in ", my_call, ":\n ", fit_screen(message), call. = FALSE)
```

I searched in the package `fixest` but do not see such an issue. I also computed the correlations among the variables as well as the fixed covariates but did not find strong correlations:
![image](https://user-images.githubusercontent.com/7501149/169706216-abadce23-4722-41ab-90d2-17aeadd0d7d9.png)

(The value is -0.26 for the correlation between treated and the time fixed effect and 0.052 for that between treated and the subject fixed effect). May I ask for your help in understanding this better? Thank you.

**Comment by kylebutts** [comment]
Do you have any periods where every unit is treated? That would be what I suspect the problem is. 

You can try running the standard TWFE regression and seeing if that runs. That is what's running and failing in the code excerpt you present:
```r
fixest::feols(outcome ~ treat | unit + time, data = df)
```

**Comment by EdJeeOnGitHub** [comment]
Just to add to @kylebutts' point, lack of high pairwise correlations doesn't necessarily imply variables aren't collinear - here `z` is clearly a linear function of binary variables `x` and `y` so fixest will throw an error but any given pairwise correlation isn't 1/-1:
```
set.seed(1)
x = rbinom(10, 1, 0.5)
y = rbinom(10, 1, 0.5)
z = -x + y
h = z + x + y + rnorm(10)
df = data.frame(
    x = x,
    y = y,
    z = z,
    h = h
)
library(fixest)
feols(
    fml = h ~ z | x + y, 
    data = df
)

cor(df[, c("x", "y", "z")])
```

**Comment by zhiyzuo** [comment]
@kylebutts   No, there is a group of control samples in my data so they are never treated. I ran TWFE first before I ran `bacondecomp`. Below is what I got from `feols` and `bacondecomp` respectively:
![image](https://user-images.githubusercontent.com/7501149/169733388-a668c0ac-e8e0-4db5-8f12-0e9896513631.png)

@EdJeeOnGitHub  Thank you for your comment. But still, in my case, the correlation is pretty low, unlike your example where  `z` is highly correlated with `x` and `y`. Moreover, `feols` works when I directly run it (as opposed to using `bacondecomp`... This is why I am very confused...

**Comment by kylebutts** [comment]
Are you able to share your dataset with me? I can try to figure it out. Or, alternatively, you could use `debug` functionality in R and I suspect you could figure out what's causing the problem

**Comment by zhiyzuo** [comment]
Yes, I sent you an email with the dataset. Thank you!

From: Kyle F Butts ***@***.***>
Date: Monday, 23 May 2022 at 11:42 AM
To: evanjflack/bacondecomp ***@***.***>
Cc: Zhiya Zuo ***@***.***>, Author ***@***.***>
Subject: Re: [evanjflack/bacondecomp] The only variable 'treated' is collinear with the fixed effects. (Issue #82)

Are you able to share your dataset with me? I can try to figure it out. Or, alternatively, you could use debug functionality in R and I suspect you could figure out what's causing the problem

**Comment by kylebutts** [comment]
Oh, I figured this out pretty quickly actually. Per the documentation, "Do not include the fixed effects in the formula."

**Comment by zhiyzuo** [comment]
Sorry, I am still confused... I did not put fixed effects in the formula. My formula only contains the outcome variable and the treatment variable. What's wrong in that?

**Comment by kylebutts** [comment]
Oh sorry! I totally misread that. The problem is treated group with time 27 and untreated group with time 2. Since your data is an unbalanced panel, when you subset to those two groups, the treatment dummy is collinear with time + unit FEs.

**Comment by zhiyzuo** [comment]
@kylebutts  Thank you so much for pointing this out! May I ask for your comment on the following three questions?

1. By "untreated group with time 2", are you referring to the control group with a time duration of only 2?
2. How did you find out it is these two pairs of samples that resulted in such an error? Is there any established procedure to identify collinearity?
3. I tried to remove the treated group with time 27 but `bacondecomp` still did not work and produced the same error regarding collinearity. I also tried removing control groups with a duration of 2 time units and got the same error.

**Comment by kylebutts** [comment]
@zhiyzuo I used `debug(bacondecomp)` which enters debugging mode when you call the function. Then I tapped through the function until it broke (iirc on the 21st 2x2 in the for loop). That was the first time it errors (could potentially be more). Overall, if you want to use a TWFE model and want to estimate it robustly, you could use my package `{did2s}`.

**Comment by zhiyzuo** [comment]
Got it. Thank you. I will also read `did2s`.

From: Kyle F Butts ***@***.***>
Date: Wednesday, 25 May 2022 at 9:54 PM
To: evanjflack/bacondecomp ***@***.***>
Cc: Zhiya Zuo ***@***.***>, Mention ***@***.***>
Subject: Re: [evanjflack/bacondecomp] The only variable 'treated' is collinear with the fixed effects. (Issue #82)

@zhiyzuo<https://github.com/zhiyzuo> I used debug(bacondecomp) which enters debugging mode when you call the function. Then I tapped through the function until it broke (iirc on the 21st 2x2 in the for loop). That was the first time it errors (could potentially be more). Overall, if you want to use a TWFE model and want to estimate it robustly, you could use my package {did2s}.
