### ISSUE TITLE
The weighted bacon estimation is not equal to the TWFE when the panel data is unbalanced.

### ISSUE THREAD

**Issue by lzy318** [evanjflack/bacon#83]
Hello,

Thanks for writing such a great package. I am using this package to do some diagnostic analysis. However, I find that when the panel data is unbalanced, the weighted bacon 2*2 estimation is not numerically equal to the TWFE estimation. For example, I use

df1 <- bacondecomp::math_reform
sample.use <- sample(c(1:dim(df1)[1]),500,replace = F)
df2 <- df1[sample.use,]
df2_bacon <- bacon(incearn_ln ~ reform_math,
                  data = df2,
                  id_var = "state",
                  time_var = "class")
sum(df2_bacon$estimate*df2_bacon$weight)
feols(incearn_ln ~ reform_math|state+class,data=df2)

The results given by bacon and twfe are different.

**Comment by kylebutts** [comment]
Hi Ziyu, 

Thanks for the reprex; always helpful for addressing. I'm under the impression that the Bacon decomposition relies on a balanced panel, so I wouldn't say the difference is necessarily an error. That being said, we should probably in the package check for a balanced panel and error otherwise to avoid this confusion

**Comment by lzy318** [comment]
Thanks a lot for the quick response. Can the conclusion in the original paper apply to the unbalanced case?

**Comment by kylebutts** [comment]
While the general issues are still there, namely $D_{it}$ is residualized on unit and time dummies and hence you're doing some sort of average of heterogeneous treatment effects. So in this sense, the conclusions of "Be careful!!" definitely still holds. However, the algebra that produces the nice 2x2 comparisons with analytical weights relies on a balanced dataset.

**Comment by lzy318** [comment]
Thanks for your clarification, really helpful.

Kyle F Butts ***@***.***>于2023年3月13日 周一11:47写道：
