### ISSUE TITLE
bacondecomp / unbalanced panel

### ISSUE THREAD

**Issue by katjasem** [evanjflack/bacon#85]
Hi, I faced an error message when using the bacon function ("Error in bacon(...: Unbalanced Panel". Researching this, I found this thread https://github.com/evanjflack/bacondecomp/issues/71 and thought the issue was resolved. Is there anything I've missed?

**Comment by kylebutts** [comment]
Hi @katjasem, the Bacon-decomposition should not work in unbalanced panels. It is an algebraic relationship that only holds in the balanced panel case. I would recommend instead of using the decomposition, instead uses a modern robust estimator that circumvents the problem all together

**Comment by katjasem** [comment]
Thanks for this super fast reply @kylebutts! The problem is that I'm digging into a paper that uses TWFE in a staggered timing setup and my intention is to show where this (my assumption) goes wrong (and not just using a more suitable estimator). The decomposition could've shed some light on this. I'll try to find another way to demonstrate this. Thanks again for the explanation!
